THULLO-55: Refactor GitHub workflow to enable the continuation of steps in case of errors at the test step

diff --git a/.github/workflows/railway_deployment.yml b/.github/workflows/railway_deployment.yml
--- a/.github/workflows/railway_deployment.yml
+++ b/.github/workflows/railway_deployment.yml
@@ -17,7 +17,8 @@ jobs:
         with:
           java-version: '11'
       - name: Run tests with gradle
-        run: ./gradlew clean test
+        run: |
+          ./gradlew clean test || exit 0
       - name: Extract test percentage
         id: percentage
         run: |
@@ -29,3 +30,9 @@ jobs:
       - name: Check coverage percentage and exit if below 70%
         if: steps.percentage.outputs.percentage < 70
         run: exit 1
+
+      # On error section
+      - name: On Error
+        if: ${{ job.status != 'success' }}
+        run: |
+          echo "There was an error in the build or test process. Please check the logs for more information."
